### ISSUE TITLE
Add a task to retrieve OAuth Token to authenticate with Azure AKS cluster

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/plugin-azure#131]
### Feature description

similarly to GCP task and https://github.com/kestra-io/plugin-ee-aws/issues/18

We should add it as a dedicated task with `token` output: `io.kestra.plugin.azure.aks.GetAuthToken`

**Comment by anna-geller** [comment]
Ben, I know that you've been working with Matt on Azure and Microsoft plugins, perhaps you could coordinate work on this one as part of the project?
