### ISSUE TITLE
Dig non Hierarchical namespace compatibility 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/plugin-azure#22]
In azure, you can create a storage account without Hierarchical namespace: 
```
Hierarchical namespace: Enabled
```
It seems that kestra need to have this to be working for storage and maybe plugin. 
It seems to have an impact on `/`, creating directories with (no name), etc ...

**Comment by anna-geller** [comment]
very old issue, is this still relevant? please reopen if so

**Comment by anna-geller** [comment]
Hierarchical namespace is a configuration in Azure Blob and should be disabled -- add docs in config guide
