### ISSUE TITLE
Add Azure Event Hubs subplugin

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/plugin-azure#38]
Docs: https://learn.microsoft.com/en-GB/azure/event-hubs/

It will likely resemble the `PutEvents` task in EventBridge for pushing events from a flow: https://kestra.io/plugins/plugin-aws/tasks/eventbridge/io.kestra.plugin.aws.eventbridge.putevents as I believe they don't support polling for messages in a queue/bus? if they do, we could add a Trigger as well: `azure.eventHubs.Trigger`

**Comment by anna-geller** [comment]
done https://kestra.io/plugins/plugin-azure#eventhubs
