### ISSUE TITLE
Add a task to invoke an Azure Function

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-azure#46]
### Feature description

Add support for invoking [Azure Functions](https://learn.microsoft.com/en-us/azure/azure-functions/) - it would be great to allow providing custom inputs to the function, invoking it, waiting for its completion, and fetching the response payload to outputs, equivalent to [Lambda Invoke task on AWS](https://kestra.io/plugins/plugin-aws/tasks/lambda/io.kestra.plugin.aws.lambda.invoke) implementation

**Comment by Ben8t** [comment]
https://learn.microsoft.com/en-us/java/api/com.microsoft.azure.functions?view=azure-java-archive

**Comment by mgabelle** [comment]
Adding some Azure Docs that helped me : 
- Create Azure function from IDEA : https://learn.microsoft.com/en-US/azure/azure-functions/functions-create-maven-intellij
- HttpTrigger : https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-http-webhook-trigger?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cfunctionsv2&pivots=programming-language-java
