### ISSUE TITLE
AbstractEventHubTask shows up in the available EventHub tasks

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/plugin-azure#75]
### Expected Behavior

AbstractEventHubTask is not a task in itself, and should not show up in https://kestra.io/plugins/plugin-azure

### Actual Behaviour

AbstractEventHubTask is not a task in itself, but shows up on https://kestra.io/plugins/plugin-azure

![Screenshot 2024-03-25 at 1 22 13 PM](https://github.com/kestra-io/plugin-azure/assets/6594483/7af805bc-be18-4b36-bf02-1fe3d49ce317)

### Steps To Reproduce

Go to page: https://kestra.io/plugins/plugin-azure and look for tasks in EventHubs section.

### Environment Information

- Kestra Version: 0.15.5
- Plugin version: 0.15.5
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker):

### Example flow

N/A

**Comment by smunteankestra** [comment]
fixed 

![Image](https://github.com/kestra-io/plugin-azure/assets/171780240/82ba7401-0288-4d0d-a869-b0fcbed2842c)
